---
- name: Setup Flask Application Environment
  hosts: local
  become: true
  tasks:
    - name: Install Python dependencies
      yum:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask

